services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/src/app
      - /src/.venv
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - fmr_network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    # The command to execute the Alembic migration script
    command: ["uv", "run", "alembic", "upgrade", "head"]

    # This service should not restart after it has successfully completed its job
    restart: "no"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fmr_network

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_PORT: ${PG_PORT}
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movies"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fmr_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - fmr_network
    
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit    
    volumes:
      - ./rabbitmq-lib:/var/lib/rabbitmq
      - ./rabbitmq-log:/var/log/rabbitmq
    networks:
      - fmr_network
  
  celery:
    # Use the same image as the main app, as it contains all the application code and dependencies
    build:
      context: .
    networks:
      - fmr_network

    env_file:
      - ./.env

    # The command to start the Celery worker
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.jobs.celery",
        "worker",
        "-l",
        "INFO",
      ]

    depends_on:
      - redis
      - migration
      - rabbitmq
networks:
  fmr_network:
    driver: bridge
